### ISSUE TITLE
Moving to "workshopper" org

### ISSUE THREAD

**Issue by rvagg** [workshopper/workshopper-wrappedexec#6]
See https://github.com/rvagg/learnyounode/issues/254, same applies here

**Comment by TimothyGu** [comment]
This should be closed now.

**Comment by martinheidegger** [comment]
@rvagg This should be closed but it looks like you are the only person that can publish a new version of workshopper-wrappedexec. Would you mind to add @workshopper/deploy _(and maybe me 😉 )_

**Comment by rvagg** [comment]
added you @martinheidegger .. I'm not really sure how to add @workshopper/deploy tbh

**Comment by martinheidegger** [comment]
@workshopper/deploy currently contains you and @julianduque, adding @julianduque would have been enough ;)
